function [fitresult, gof] = diameter(Position, Power2, Uncertainty)
%CREATEFIT(POSITION,POWER2)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : Position
%      Y Output: Power2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Nov-2019 08:22:11


%% Fit: 'untitled fit 2'.
[xData, yData, error] = prepareCurveData( Position, Power2, Uncertainty(1:12) );

% Set up fittype and options.
ft = fittype( '0.89*(0.5*erf(sqrt(2)*(-x)/b)+0.5)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = 0.537247202379736;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
hold on
errorbar(xData, yData, error, '.')
hold off
legend( h, 'Power vs. Position', 'Power vs. Position', 'Location', 'NorthEast', 'Interpreter', 'none' );
title('Power vs Knife Edge Position')
text(-1.4,0,sprintf('Fit = 0.89*(0.5*erf(sqrt(2)*(-x)/a)+0.5)\na = 0.6924 (0.5922, 0.7927)\nSSE = %g\nRsq = %g\nAdj = %g\nRMSE = %g',gof.sse,gof.rsquare,gof.adjrsquare,gof.rmse))
% Label axes
xlabel( 'Position (mm)', 'Interpreter', 'none' );
ylabel( 'Power (mW)', 'Interpreter', 'none' );
grid on


