function [fitresult, gof] = experiment2(ChannelNumber, PhotopeakEnergykeV, FWHMkeV)
%CREATEFIT(CHANNELNUMBER,PHOTOPEAKENERGYKEV)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : ChannelNumber
%      Y Output: PhotopeakEnergykeV
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Nov-2019 16:23:48


%% Fit: 'untitled fit 1'.
[xData, yData, error] = prepareCurveData( ChannelNumber, PhotopeakEnergykeV, FWHMkeV );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
hold on;
errorbar( xData, yData, error, '.');
hold off;
legend( h, 'Data Points', 'Best Fit', 'Location', 'NorthWest', 'Interpreter', 'none' );
title("Photopeak Energy vs. Channel Number")
text(400,300,sprintf('Fit = a*x^2+b*x+c\nSSE = %g\nRsq = %g\nAdj = %g\nRMSE = %g',gof.sse,gof.rsquare,gof.adjrsquare,gof.rmse))
myCoeffs = coeffvalues(fitresult);
intervals = confint(fitresult);
text(0, 1000, sprintf('a = %g (%g, %g)\nb = %g (%g, %g)\nc = %g (%g, %g)', myCoeffs(1), intervals(1), intervals(2), myCoeffs(2), intervals(3), intervals(4), myCoeffs(3), intervals(5), intervals(6)))
% Label axes
xlabel( 'ChannelNumber', 'Interpreter', 'none' );
ylabel( 'Photopeak Energy (keV)', 'Interpreter', 'none' );
grid on


