function [fitresult, gof] = LeadCs137(Thicknessmgcm2, LogofNetCountRate)
%CREATEFIT(THICKNESSMGCM2,LOGOFNETCOUNTRATE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Thicknessmgcm2
%      Y Output: LogofNetCountRate
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 25-Nov-2019 06:53:08


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Thicknessmgcm2, LogofNetCountRate );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Data Points', 'Best Fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
title("Logarithm of Net Count Rate vs. Absorber Thickness")
text(1000, 0.8, sprintf('Fit = a*x+b\nSSE = %g\nRsq = %g\nAdj = %g\nRMSE = %g',gof.sse,gof.rsquare,gof.adjrsquare,gof.rmse))
myCoeffs = coeffvalues(fitresult);
intervals = confint(fitresult);
text(1000, 0.4, sprintf('a = %g (%g, %g)\nb = %g (%g, %g)', myCoeffs(1), intervals(1), intervals(2), myCoeffs(2), intervals(3), intervals(4)))
% Label axes
xlabel( 'Thickness (mg/cm^2)', 'Interpreter', 'none' );
ylabel( 'Logarithm of Net Count Rate (counts/s)', 'Interpreter', 'none' );
grid on


